version: "2"
services:
  referencedata-extension:
    image: openlmis/dev:5.2
    volumes:
      - '.:/app'
      - 'gradlecache:/gradle'
    env_file: .env
volumes:
  gradlecache:
    external: false
